### ISSUE TITLE
Symbol20_18, Line 2	1086: Syntax error: expecting semicolon before rightparen.

### ISSUE THREAD

**Issue by ChanMario** [anthonyfok/buzz-flash#10]
After pressing Command+Return to Test Movie (2015-03-26 version, around 12 noon), the follow compile error is encountered:

    Symbol20_18, Line 2	1086: Syntax error: expecting semicolon before rightparen

The cause is yet unknown, but it may have something to do with the recent addition of a translucent flash movie on Scene 2 (when the user hovers over a rocket button.)

**Comment by anthonyfok** [comment]
This problem seems to have disappeared once the inserted MP4 video clip was deleted.

Mario then proceeded to use Adobe Media Encoder (AME) CS6 to convert the two MP4 video clips to F4V format, and that seems to be working!  :-)  So, shall we close this issue, @ChanMario?
