### ISSUE TITLE
Adding a "typing text" effect to the presentation in Scene 3

### ISSUE THREAD

**Issue by ChanMario** [anthonyfok/buzz-flash#12]
https://www.developphp.com/video/Flash/Typing-Text-Animation-Array-Tutorial

This website has mentioned the ActionScript about the special text effects, with the following sample code:

```ActionScript
var myString:String = "Put as much string data as you wish to here";
var myArray:Array = myString.split("");
addEventListener(Event.ENTER_FRAME, frameLooper);
function frameLooper(event:Event):void
{
    if (myArray.length > 0) {
        tf.appendText(myArray.shift());
    } else {
        removeEventListener(Event.ENTER_FRAME, frameLooper);
    }
}
```

And I wants to apply this special effect on the scene 3 in frame1 , 2 and 8.
However, I do not know how to insert my contents in this script.
Please suggest me how to archieve this. Thank you

**Comment by anthonyfok** [comment]
Recommend actions:

1. View the YouTube video on that website https://www.developphp.com/video/Flash/Typing-Text-Animation-Array-Tutorial that you provided.
2. In Flash CS6, create a new Flash project and try to make the typing text work.
3. One you have got it working in your test project, try to apply what you've learned into your Final Project.  At least try to get it working on Frame 1.
4. Once successful, try to apply the same on the other two frames.

If you encounter any troubles, please do not hesitate to let me know.  Thanks!

Anthony

**Comment by anthonyfok** [comment]
Awesome!  Mario got it to work himself!  Mission accomplished!
