### ISSUE TITLE
The `.fla` file is too big

### ISSUE THREAD

**Issue by anthonyfok** [anthonyfok/buzz-flash#16]
For some reason, the current `.fla` file is a whopping 137MB even though our video files are no longer embedded into the timeline.

There are indeed some unused items in the library, and according to [this post on Adobe's forum](https://forums.adobe.com/thread/1579513), we can easily Select Unused Items and delete them from the Library.

However, doing that only resulted a roughly 3MB saving.  The `.fla` file is now about 134MB.

Oh, wait, there *are* indeed some leftover `.flv` files in the Library!

* Buzzcommercial.flv
* Buzzcommercial.flv 1
* buzzlanding.flv
* buzzlanding.flv 1

And indeed they seem to be the culprit.  After manually deleting them from the Library and saving the `.fla` file, the file size is now 38MB, a much more normal and acceptable size.

**Comment by ChanMario** [comment]
Yes, removing the leftover `.flv` files inside the Library reduces the filesize to 41MB.  Problem solved!
