### ISSUE TITLE
Need to stop music and movie (a) when leaving a scene (b) when mouse cursor moves off a button

### ISSUE THREAD

**Issue by anthonyfok** [anthonyfok/buzz-flash#7]
As Mario reported:

> The music and movie keep playing even when I go to another scene.
> In the Scene 5, there is a invisible home button above the play movie button.
> The movie sound wont stop even when u pressed back to home page.
>
> The content music of scene 4,  how to set the sound to stop when I am not overing the button.

**Comment by anthonyfok** [comment]
I think it is probably as simple as calling

    movieClipName.stop();

where appropriate, probably right before a `gotoAndPlay()` call, and in a `mouseOut` event handler?

**Comment by anthonyfok** [comment]
Use MOUSE_OUT event under "Event Handler" in code snippet

**Comment by ChanMario** [comment]
http://stackoverflow.com/questions/5950434/stop-music-on-mouse-out

You need to keep a reference to the SoundChannel created when playing a Sound. A Sound represents a sound, while a SoundChannel represents the playback of a sound, and it is the playback, that you want to stop.

**Comment by anthonyfok** [comment]
Mario found this function, which is good at stopping all sounds:

```ActionScript
SoundMixer.stopAll();
```

However, I do not yet know how to get the music/video to play again after a `SoundMixer.stopAll();` call.

Another method is to turn down the volume to 0 by using this great tip, "Adjust Global Sound Volume in Actionscript 3", from http://www.as3blog.org/2011/05/03/adjust-global-sound-volume-in-actionscript-3/:

```ActionScript
import flash.media.SoundMixer;
import flash.media.SoundTransform;

// volume limits are 0 to 1 (0.1,0.2,0.3,...,1)
SoundMixer.soundTransform = new SoundTransform(0);
```

**Comment by anthonyfok** [comment]
More or less fixed the overlapping audio issue with the movies in Scene 2.  The solution is to put the video right on the stage instead of hidden inside the "Over" frame of the button, and to use the methodology outlined in the answer here: http://stackoverflow.com/questions/13462973/how-to-entirely-remove-an-flvplayback-from-stage-when-going-to-another-flvplayba/14314674#14314674

**Comment by anthonyfok** [comment]
With only one single `movieScreen`, things are actually much easier to handle, as we can stop the movie or change the movie source MPEG-4 file very cleanly whenever we wish.

Here is the relevant code on Scene 2, Actions : Frame 1:

```ActionScript
movieScreen.visible = false;

function pauseVideo(event:MouseEvent):void
{
	if (movieScreen) {
		movieScreen.pause();
		movieScreen.visible = false;
	}
}

function playStoryVideo(event:MouseEvent):void
{
	if (movieScreen) {
		movieScreen.source = "Toy Story 2 - Buzz Lightyear opening scene HD-EyGuBM1ELf4.f4v";
		movieScreen.visible = true;
		movieScreen.play();
	}
}

function playBuzzVideo(event:MouseEvent):void
{
	if (movieScreen) {
		movieScreen.source = "Buzz Lightyear commercial.f4v";
		movieScreen.visible = true;
		movieScreen.play();
	}
}
```

At the various exit points, we "clean up" as follows when the movie is playing (the `movieScreen` related lines):

```ActionScript
story_btn.addEventListener(MouseEvent.CLICK, jumpToScene5);
function jumpToScene5(event:MouseEvent):void
{
	stage.removeEventListener(MouseEvent.MOUSE_MOVE, followCursor);
	movieScreen.stop();
	movieScreen.visible = false;
	gotoAndPlay(1, "Scene 5");
}

/* This adds an event listener to the "My Body Functions" rocket button
   to jump to Scene 4 where each of Buzz's body parts are explained.
*/
Bodyfunc_btn.addEventListener(MouseEvent.CLICK, jumpToScene4);
function jumpToScene4(event:MouseEvent):void
{
	stage.removeEventListener(MouseEvent.MOUSE_MOVE, followCursor);
	movieScreen.stop();
	movieScreen.visible = false;
	gotoAndPlay(1, "Scene 4" );
}
```

And, on the "Home Button", when the song "You've got a friend in me" is playing, we did this instead (the `soundMixer` related lines):

```ActionScript
btn_coverpage.addEventListener(MouseEvent.CLICK, jumpToCoverPage);
function jumpToCoverPage(event:MouseEvent):void
{
	stage.removeEventListener(MouseEvent.MOUSE_MOVE, followCursor);
	SoundMixer.stopAll();
	SoundMixer.soundTransform = new SoundTransform(1);
	gotoAndPlay(1150, "Scene 1");
}
```
